[project]
name = "pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.4.3",
    "osmium>=4.2.0",
    "pyproj>=3.7.2",
    "shapely>=2.1.2",
]

[tool.black]
line-length = 100
